config/routes.rb
Tenk::Application.routes.draw do
  resources :activity_types

  resources :activities

  devise_for :users

  root :to => 'pages#home'
  get 'home' => 'pages#home'
  get 'ipsum' => 'pages#ipsum'
  get 'user' => 'pages#user'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  attr_accessible :name, :activity_type_id, :duration_hours
  belongs_to :user
  belongs_to :activity_type
end

app/models/activity_type.rb
class ActivityType < ActiveRecord::Base
  attr_accessible :name
  has_many :activities
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :confirmed_at
  # attr_accessible :title, :body
  has_many :activities
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activities }
    end
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
    @activity = Activity.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/new
  # GET /activities/new.json
  def new
    @activity = Activity.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity }
    end
  end

  # GET /activities/1/edit
  def edit
    @activity = Activity.find(params[:id])
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = current_user.activities.build(params[:activity])

    respond_to do |format|
      if @activity.save
        format.html { redirect_to :root, notice: 'Activity was successfully created.' }
        format.json { render json: @activity, status: :created, location: @activity }
      else
        format.html { render action: "new" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activities/1
  # PUT /activities/1.json
  def update
    @activity = Activity.find(params[:id])

    respond_to do |format|
      if @activity.update_attributes(params[:activity])
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy

    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/activity_types_controller.rb
class ActivityTypesController < ApplicationController
  # GET /activity_types
  # GET /activity_types.json
  def index
    @activity_types = ActivityType.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @activity_types }
    end
  end

  # GET /activity_types/1
  # GET /activity_types/1.json
  def show
    @activity_type = ActivityType.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @activity_type }
    end
  end

  # GET /activity_types/new
  # GET /activity_types/new.json
  def new
    @activity_type = ActivityType.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @activity_type }
    end
  end

  # GET /activity_types/1/edit
  def edit
    @activity_type = ActivityType.find(params[:id])
  end

  # POST /activity_types
  # POST /activity_types.json
  def create
    @activity_type = ActivityType.new(params[:activity_type])

    respond_to do |format|
      if @activity_type.save
        format.html { redirect_to @activity_type, notice: 'Activity type was successfully created.' }
        format.json { render json: @activity_type, status: :created, location: @activity_type }
      else
        format.html { render action: "new" }
        format.json { render json: @activity_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /activity_types/1
  # PUT /activity_types/1.json
  def update
    @activity_type = ActivityType.find(params[:id])

    respond_to do |format|
      if @activity_type.update_attributes(params[:activity_type])
        format.html { redirect_to @activity_type, notice: 'Activity type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @activity_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activity_types/1
  # DELETE /activity_types/1.json
  def destroy
    @activity_type = ActivityType.find(params[:id])
    @activity_type.destroy

    respond_to do |format|
      format.html { redirect_to activity_types_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  before_filter :authenticate_user!, except: [:landing, :ipsum]

  def landing
    render :layout => 'landing'
  end

  def home
    @my_activities = current_user.activities
    
  end

  def user
    @user = current_user
    @my_activities = current_user.activities

  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/activity_types_helper.rb
module ActivityTypesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/content_helper.rb
module ContentHelper
  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/activities/_form.html.haml
= form_for @activity do |f|
  - if @activity.errors.any?
    #error_explanation
      %h2= "#{pluralize(@activity.errors.count, "error")} prohibited this activity from being saved:"
      %ul
        - @activity.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :activity_type_id
    = collection_select(:activity, :activity_type_id, ActivityType.find(:all), :id, :name)
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :duration_hours
    = f.text_field :duration_hours
  .actions
    = f.submit 'Save'

app/views/activities/edit.html.haml
%h1 Editing activity

= render 'form'

= link_to 'Show', @activity
\|
= link_to 'Back', activities_path

app/views/activities/index.html.haml
%h1 Listing activities

%table
  %tr
    %th
    %th
    %th

  - @activities.each do |activity|
    %tr
      %td= link_to 'Show', activity
      %td= link_to 'Edit', edit_activity_path(activity)
      %td= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Activity', new_activity_path

app/views/activities/new.html.haml
%h1 New activity

= render 'form'

= link_to 'Back', activities_path

app/views/activities/show.html.haml
%p#notice= notice

=@activity.name


= link_to 'Edit', edit_activity_path(@activity)
\|
= link_to 'Back', activities_path

app/views/activity_types/_form.html.haml
= form_for @activity_type do |f|
  - if @activity_type.errors.any?
    #error_explanation
      %h2= "#{pluralize(@activity_type.errors.count, "error")} prohibited this activity_type from being saved:"
      %ul
        - @activity_type.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .actions
    = f.submit 'Save'

app/views/activity_types/edit.html.haml
%h1 Editing activity_type

= render 'form'

= link_to 'Show', @activity_type
\|
= link_to 'Back', activity_types_path

app/views/activity_types/index.html.haml
%h1 Listing activity_types

%table
  %tr
    %th Title
    %th
    %th
    %th

  - @activity_types.each do |activity_type|
    %tr
      %td= activity_type.title
      %td= link_to 'Show', activity_type
      %td= link_to 'Edit', edit_activity_type_path(activity_type)
      %td= link_to 'Destroy', activity_type, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Activity type', new_activity_type_path

app/views/activity_types/new.html.haml
%h1 New activity_type

= render 'form'

= link_to 'Back', activity_types_path

app/views/activity_types/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @activity_type.title

= link_to 'Edit', edit_activity_type_path(@activity_type)
\|
= link_to 'Back', activity_types_path

app/views/application/_signup.html.haml
%h2 Sign up
= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f|
  = devise_error_messages!
  %div
    = f.label :email
    %br/
    = f.email_field :email
  %div
    = f.label :password
    %br/
    = f.password_field :password
  %div
    = f.label :password_confirmation
    %br/
    = f.password_field :password_confirmation
  %div= f.submit "Sign up"
= render "devise/shared/links"

app/views/layouts/application.html.haml
!!! 5
/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en">
/[if IE 7] <html class="no-js lt-ie9 lt-ie8" lang="en">
/[if IE 8] <html class="no-js lt-ie9" lang="en">
/ Consider adding a manifest.appcache: h5bp.com/d/Offline
/ [if gt IE 8]><!
%html.no-js{:lang => "en"}
  / <![endif]
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "10k"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"

    = javascript_include_tag "http://cdnjs.cloudflare.com/ajax/libs/bonsai/0.4/bonsai.min.js"
    = stylesheet_link_tag "http://fonts.googleapis.com/css?family=Ubuntu:400,700|Droid+Serif:400,700,400italic", "application", :media => "all"

    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")

  %body
    %header#primaryHeader{:role => "banner"}
      .container
        .clearfix
          .span3
            %h1#logo= link_to "10K", home_path
          %nav#primaryNavigation.span9
            %ul.horizontal
              %li= link_to "Dashboard", "#"
              %li= link_to "Activities", "#"
          %nav#userCorner
            %ul.horizontal
              - if user_signed_in?
                = current_user.email
                = link_to("Sign Out", destroy_user_session_path, :method => :delete )
              - else
                =link_to("Sign In", new_user_session_path)
                |
                =link_to("Sign Up", new_user_registration_path)

    .container
      .row
        .span12
          -# TODO: bootstrap_flash
          = yield
    
      %footer
    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/layouts/landing.html.haml
!!! 5
/[if lt IE 7] <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en">
/[if IE 7] <html class="no-js lt-ie9 lt-ie8" lang="en">
/[if IE 8] <html class="no-js lt-ie9" lang="en">
/ Consider adding a manifest.appcache: h5bp.com/d/Offline
/ [if gt IE 8]><!
%html.no-js{:lang => "en"}
  / <![endif]
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Starters' App"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "http://html5shim.googlecode.com/svn/trunk/html5.js"
    = stylesheet_link_tag "http://fonts.googleapis.com/css?family=Droid+Sans:400,700", "application", :media => "all"

    %link(href="images/apple-touch-icon-144x144.png" rel="apple-touch-icon-precomposed" sizes="144x144")
    %link(href="images/apple-touch-icon-114x114.png" rel="apple-touch-icon-precomposed" sizes="114x114")
    %link(href="images/apple-touch-icon-72x72.png" rel="apple-touch-icon-precomposed" sizes="72x72")
    %link(href="images/apple-touch-icon.png" rel="apple-touch-icon-precomposed")
    %link(href="images/favicon.ico" rel="shortcut icon")

  %body
    %header#primaryHeading.container
      .clearfix
        %h1#branding.span3= link_to "10K", home_path
        %nav#usercorner.span9
          - if user_signed_in?
            = current_user.email
            |
            = link_to("Sign Out", destroy_user_session_path, :method => :delete )
          - else
            =link_to("Sign In", new_user_session_path)
            |
            =link_to("Sign Up", new_user_registration_path)
          %a.brand{ :href => root_path }
            10k
          .container.nav-collapse
            %ul.nav
              %li= link_to "Link 1"

    .container
      .row
        .span12
          -# TODO: bootstrap_flash
          = yield
    
      %footer
        %p &copy; Starters'App 2012

    /
      Javascripts
      \==================================================
    / Placed at the end of the document so the pages load faster
    = javascript_include_tag "application"

app/views/pages/home.html.haml
=link_to("Add Activity", new_activity_path)
%br
-@my_activities.each do |a|
  =a.name
  %br

app/views/pages/ipsum.html.erb
<h1>HTML Ipsum Presents</h1>
         
<p><strong>Pellentesque habitant morbi tristique</strong> senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. <em>Aenean ultricies mi vitae est.</em> Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, <code>commodo vitae</code>, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. <a href="#">Donec non enim</a> in turpis pulvinar facilisis. Ut felis.</p>

<h2>Header Level 2 <br> Second line</h2>
         
<ol>
   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
   <li>Aliquam tincidunt mauris eu risus.</li>
</ol>

<blockquote><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus magna. Cras in mi at felis aliquet congue. Ut a est eget ligula molestie gravida. Curabitur massa. Donec eleifend, libero at sagittis mollis, tellus est malesuada tellus, at luctus turpis elit sit amet quam. Vivamus pretium ornare est.</p></blockquote>

<h3>Header Level 3</h3>

<ul>
   <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
   <li>Aliquam tincidunt mauris eu risus.</li>
</ul>

<pre><code>
#header h1 a { 
  display: block; 
  width: 300px; 
  height: 80px; 
}
</code></pre>

<form action="#" method="post">
    <div>
         <label for="name">Text Input:</label>
         <input type="text" name="name" id="name" value="" tabindex="1" />
    </div>

    <div>
         <h4>Radio Button Choice</h4>

         <label for="radio-choice-1">Choice 1</label>
         <input type="radio" name="radio-choice-1" id="radio-choice-1" tabindex="2" value="choice-1" />

     <label for="radio-choice-2">Choice 2</label>
         <input type="radio" name="radio-choice-2" id="radio-choice-2" tabindex="3" value="choice-2" />
    </div>

  <div>
    <label for="select-choice">Select Dropdown Choice:</label>
    <select name="select-choice" id="select-choice">
      <option value="Choice 1">Choice 1</option>
      <option value="Choice 2">Choice 2</option>
      <option value="Choice 3">Choice 3</option>
    </select>
  </div>
  
  <div>
    <label for="textarea">Textarea:</label>
    <textarea cols="40" rows="8" name="textarea" id="textarea"></textarea>
  </div>
  
  <div>
      <label for="checkbox">Checkbox:</label>
    <input type="checkbox" name="checkbox" id="checkbox" />
    </div>

  <div>
      <input type="submit" value="Submit" />
    </div>
</form>

app/views/pages/user.html.haml
#SkillsChart

#HoursChart

:javascript
  bonsai.run(document.getElementById('SkillsChart'), {url: '/assets/PieChart.js', 
    code: function() {
      new PieChart({ 
        'BonsaiJS': 5,
        'Ruby on Rails': 20,
        'HTML/CSS': 30,
        'CoffeeScript': 8,
        'jQuery': 19,
        'AngularJS': 18
      });
    },
    width: 700, height: 400 });

  bonsai.run(document.getElementById('HoursChart'), {url: '/assets/PieChart.js', 
    code: function() {
      new PieChart({ 
        'BonsaiJS': 5,
        'Ruby on Rails': 20,
        'HTML/CSS': 30,
        'CoffeeScript': 8,
        'jQuery': 19,
        'AngularJS': 18
      });
    },
    width: 700, height: 400 });

=link_to("Add Activity", new_activity_path)
%br
-@my_activities.each do |a|
  =a.name
  %br